#!/bin/bash
set -eu
set -o pipefail

GUEST_USERNAME=${GUEST_USERNAME:-"ubuntu"}

echo "Bypassing Docker HTTPS repo. Installing docker.io from standard Ubuntu HTTP repo..."
export DEBIAN_FRONTEND=noninteractive
apt-get update || true
apt-get install -y -qq docker.io >/dev/null
apt-get clean

echo "Adding ${GUEST_USERNAME} user to docker group"
usermod -aG docker ${GUEST_USERNAME}
systemctl enable docker