#!/bin/bash
set -e
# Thay thế bằng phương thức thêm repo an toàn và hiện đại
apt-get update || true
apt-get install -y wget gnupg2 lsb-release curl
wget https://repo.percona.com/apt/percona-release_latest.generic_all.deb
dpkg -i percona-release_latest.generic_all.deb
percona-release setup ps80
